= Data model: cycling

This data model uses the concept of cycling statistics that have cyclists and races. 
Cyclists have personal statistics, such as name, age, and team.
Races have information about names, routes, and winners.

Typical data types that are in use in most data models, such as text, UUIDs, and integers are easy to use for columns in this data model.
Cyclists can have unique user-ids that are UUIDs, names are text, and birthdate that is a date data type.
Race start and end times can use the timestamp data type.
Teams that a rider has been a member of is a good example of a set.
// FIX NEXT LINES
// the authors of a book are a good example of a list (ordered set).
// Reader badges can be stored in a map, where the key is the level of badge and and the value is the date of earning the level.
// The countries that a reader has lived in can provide a vehicle  for using tuples, to store the country name, and arrival and departure dates.
// Reviews and addresses are excellent examples of user-defined types (UDTs).

In short, many of the data types can be incorporated into this data model, so that all usage of the data types available to our many interfaces to Cassandra can be shown.

include::page$conceptual-cycling.adoc[leveloffset="+1"]

include::page$logical-cycling.adoc[leveloffset="+1"]

include::page$physical-cycling.adoc[leveloffset="+1"]

include::page$schema-cycling.adoc[leveloffset="+2"]

include::page$queries-cycling.adoc[leveloffset="+2"]

include::page$sample-data-cycling.adoc[leveloffset="+1"]
