#antora:
#  extensions:
#  - require: ./lib/select-component-descriptor.js
#    default_profile: library
#  - ./lib/inject-collector-config.js
#  - '@antora/collector-extension'
#  - '@antora/atlas-extension'

site:
  title: LLP Data Models
#  keys:
#    profile: library

output:
  dir: ./../build/site

content:
  edit_url: ~
  sources:
  - url: ./..
    branches: HEAD
    start_paths: docs-src/core

ui:
  bundle:
    url: https://github.com/riptano/antora-ui-docs/releases/latest/download/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui
  output_dir: assets

asciidoc:
  attributes:
    page-pagination: ''
    sectanchors: ''
    sectlinks: ''
    id-prefix: ''
    id-separator: '-'

    ASTRA_CLUSTER_ID: '8319febd-e7cf-4595-81e3-34f45d332d2a'
    ASTRA_REGION: 'us-east1'
    ASTRA_USERNAME: 'polandll'
    ASTRA_PASSWORD: '12345abcd'

    local-url: 'localhost'
    local-port: ':8180'
    local-rest-schema: '/v2/schemas/keyspaces'

    auth_token: '$ASTRA_DB_APPLICATION_TOKEN'
    base_auth_url: 'http://$ASTRA_CLUSTER_ID-$ASTRA_REGION.apps.astra.datastax.com:8081'
    base_auth_api_path: '/v1/auth'
    cass_user: 'cassandra' # switch to auth_username
    cass_passwd: 'cassandra' # switch to auth_password

    base_rest_url: 'https://$ASTRA_CLUSTER_ID-$ASTRA_REGION.apps.astra.datastax.com'
    base_doc_url: 'https://$ASTRA_CLUSTER_ID-$ASTRA_REGION.apps.astra.datastax.com'
    base_graphql_url: 'https://$ASTRA_CLUSTER_ID-$ASTRA_REGION.apps.astra.datastax.com:8080'

    base_rest_schema: '/api/rest/v2/schemas/keyspaces'
    base_doc_schema: '/api/rest/v2/schemas/namespaces'
    base_gql_schema: '/api/graphql-schema'

    base_gql_admin: '/api/graphql-admin'

    base_rest_api: '/api/rest/v2/keyspaces'
    base_doc_api: '/api/rest/v2/namespaces'
    base_gql_api: '/api/graphql'

    rkeyspace: 'users_keyspace'
    rkeyspace-dcs: 'users_keyspace-dcs'
    rpartitionkey: 'firstname'
    rclusteringkey: 'lastname'
    rtable: 'users'
    user1fn: 'Mookie'
    user1ln: 'Betts'
    user2fn: 'Janesha'
    user2ln: 'Doesha'

    # namespace: 'myworld'
    collection: 'fitness'
    user1: 'Janet'
    user2: 'Joey'
    user2a: 'Joseph'
    user3: 'Martha'

    gkeyspace: 'library'
    gtable1: 'book'
    gtable2: 'reader'

    support_url: 'https://houston.datastax.com/hc/requests/new'
    astra_docs_base_url: 'https://docs.datastax.com/en/astra/docs'

    keyspace: 'library'
    namespace: 'library'

  extensions:
  - '@asciidoctor/tabs'
